name: Trigger auto deployment for n4h

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/n4h-AutoDeployTrigger-bc7435bb-6dd3-40c2-bc6d-190eb8e2d432.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.N4H_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.N4H_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.N4H_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: docker.io
          registryUsername: ${{ secrets.N4H_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.N4H_REGISTRY_PASSWORD }}
          containerAppName: n4h
          resourceGroup: n4h
          imageToBuild: pedrozetterstrom/n4h:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


